services:

  cypress:
    image: cypress/included:12.17.4
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CYPRESS_baseUrl=http://pong-frontend:5173
    depends_on:
      - pong-frontend
      - pong-backend
    command: npx cypress run
    networks:
      - transcedence-network

  pong-frontend:
    build:
      context: ./pong-frontend
      dockerfile: Dockerfile
    container_name: pong-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./pong-frontend:/app
      - ./tests/frontend:/app/vitest
      - /app/node_modules
    environment:
      - VITE_PONG_BACKEND_API=http://localhost:3000
      - VITE_PONG_BACKEND_WEBSOCKET=ws://localhost:3000/ws
      - NODE_ENV=development
    command: npm run dev
    networks:
      - transcedence-network

  pong-backend:
    build:
      context: ./pong-backend
      dockerfile: Dockerfile
    container_name: pong-backend
    ports:
      - "3000:3000"
    volumes:
      - ./pong-backend:/app
      - ./tests/backend:/app/vitest
      - /app/node_modules
      - ./hardhat/artifacts/contracts/TournamentScores.sol:/app/artifacts
      - ./hardhat/ignition/deployments/chain-31337/deployed_addresses.json:/app/deployed/deployed_addresses.json
    environment:
      - NODE_ENV=development
      - ADRESS=192.0.7
      - RPC_URL=http://hardhat:8545
      - RESEND_API_KEY=${RESEND_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TIME=${JWT_TIME}
    command: npm run dev
    networks:
      - transcedence-network
    depends_on:
      hardhat:
        condition: service_healthy
    env_file:
      - .env

  hardhat:
    image: hardhat-node
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    container_name: hardhat-node
    ports:
      - "8545:8545"
    volumes:
      - ./hardhat:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8545 | grep -q '{}' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    networks:
      - transcedence-network


volumes:
  pong-backend-data:

networks:
  transcedence-network:
    driver: bridge