services:

  cypress:
    image: cypress/included:12.17.4
    working_dir: /e2e
    volumes:
      - ./cypress:/e2e
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    depends_on:
      - pong-frontend
      - pong-backend
    command: npx cypress run

  pong-frontend:
    build:
      context: ./pong-frontend
      dockerfile: Dockerfile
    container_name: pong-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./pong-frontend:/app
      - /app/node_modules
    environment:
      - VITE_PONG_BACKEND_API=http://localhost:3000
      - VITE_PONG_BACKEND_WEBSOCKET=ws://localhost:3000/ws
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - transcedence-network

  pong-backend:
    build:
      context: ./pong-backend
      dockerfile: Dockerfile
    container_name: pong-backend
    ports:
      - "3000:3000"
    volumes:
      - ./pong-backend:/app
      - /app/node_modules
    environment:
      - ADRESS=192.0.7
      - RPC_URL=http://blockchain:8545
      - RESEND_API_KEY=${RESEND_API_KEY}
    command: npm run dev
    networks:
      - transcedence-network
    env_file:
      - .env

  blockchain:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    container_name: hardhat-node
    ports:
      - "8545:8545"
    volumes:
      - ./hardhat:/app
      - /app/node_modules
    command: npx hardhat node
    networks:
      - transcedence-network


volumes:
  pong-backend-data:

networks:
  transcedence-network:
    driver: bridge