name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-tests:
    name: frontend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create empty .env file
        run: touch .env

      - name: Build frontend container
        run: docker compose build pong-frontend

      - name: Run frontend tests
        run: docker compose run --rm pong-frontend npx vitest --run --reporter verbose

      - name: Clean up
        run: docker compose down --volumes

  backend-tests:
    name: backend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create empty .env file
        run: touch .env


      - name: Build backend container
        run: docker compose build pong-backend

      - name: Create database
        run: docker compose run --rm pong-backend tsx /app/database/init.ts

      - name: Run backend tests
        run: docker compose run --rm pong-backend npx vitest --run --reporter verbose

      - name: Clean up
        run: docker compose down --volumes

