name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-tests:
    name: frontend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend Docker image
        working-directory: pong-frontend
        run: docker build -t pong-frontend .

      - name: Run frontend tests inside container
        run: docker run --rm pong-frontend npm run test

  backend-tests:
    name: backend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        working-directory: pong-backend
        run: docker build -t pong-backend .

      - name: Start backend server
        run: npm run dev

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Run backend tests inside container
        run: docker run --rm pong-backend /bin/sh -c "npm run database && npm run test"